### ISSUE TITLE
Credential leakage

### ISSUE THREAD

**Issue by ayethatsright** [ccpcc1/Social-cooking#3]
Hi/Ola,

I'm a security researcher in Wales.  I noticed you have your .PublishSettings file with your Azure credentials publically accessible in your repo:

https://github.com/ccpcc1/Social-cooking/blob/master/SocialCooking/socialCookingWeb.PublishSettings

Might want to remove them.

Regards

Steve

**Comment by josemanuelep** [comment]
Hi Friend. 
Thank for the issue, thank you very much.
Now I deleted the file.

Regards you too.
